# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4773a692d13169dd0b018eb83a65ef67557e5077c9c5496052bcc464ddb9c52d40ecefe8813c3c8c483a34cac8a192da1af2ec611f05f768de6c4066a4dac15

test:
  secret_key_base: b5881a115981650dc74a7c0b464da96873e91d053a58b6624b377067e6b1867b21fb5238a69012f879bee0408f2ade59e331286314e9d1cef1fe0a5a1619e0aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
